# Generated by Django 5.0.6 on 2024-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0003_item_alter_chat_id_alter_medical_id_alter_ment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contactnumber',
            new_name='contactNumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='collegename',
        ),
        migrations.AddField(
            model_name='profile',
            name='Department',
            field=models.CharField(choices=[('IT Department', 'IT Department'), ('HR Department', 'HR Department'), ('Logistics Department', 'Logistics Department'), ('D Staff ', 'D Staff ')], default='IT Department', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Gandhinagar', 'Gandhinagar')], max_length=100),
        ),
    ]
