# Generated by Django 5.0.1 on 2024-06-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GRsystem", "0004_rename_contactnumber_profile_contactnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="Type_of_complaint",
            field=models.CharField(
                choices=[
                    ("Workplace", "Workplace"),
                    ("Hardware", "Hardware"),
                    ("Management", "Management"),
                    ("IT", "IT"),
                    ("Other", "Other"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_user",
            field=models.CharField(
                choices=[("employee", "employee"), ("hradmin", "hradmin")],
                default="student",
                max_length=20,
            ),
        ),
    ]
